const FIELD_LABELS: Record<string, string> = {
  // Рейс
  revenue_eur: 'Фрахт (€)',
  driver_id: 'Водитель',
  truck_id: 'Тягач',
  client_id: 'Клиент',
  start_date: 'Дата старта',
  end_date: 'Дата финиша',
  route: 'Маршрут',
  client_request_number: '№ заявки клиента',
  start_fuel_level: 'Остаток топлива (л)',
  status: 'Статус',
  // Клиент
  name: 'Название',
  contact_person: 'Контактное лицо',
  phone: 'Телефон',
  email: 'Email',
  // Локация
  type: 'Тип локации',
  company_name: 'Организация',
  postal_code: 'Почтовый код',
  city: 'Город',
  address: 'Адрес',
  // Подрядчик / водитель / общее
  full_name: 'Полное название',
  tax_id: 'NIP',
  country: 'Страна',
  notes: 'Заметки',
  // Водитель
  first_name: 'Имя',
  last_name: 'Фамилия',
  passport_number: '№ паспорта',
  passport_expiry: 'Срок паспорта',
  visa_expiry: 'Срок визы',
  license_number: '№ прав',
  license_expiry: 'Срок прав',
  tachograph_card_number: '№ карты тахографа',
  tachograph_card_expiry: 'Срок карты тахографа',
  code_95_expiry: 'Срок Код 95',
  adr_expiry: 'Срок АДР',
  date_of_birth: 'Дата рождения',
};
